[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "prisma", "xlsx"]
  included_files = ["node_modules/.prisma/client/**", "prisma/**"]

[dev]
  framework = "#static"
